
<!--<button type="button" class="scalable save" -->
<!--        onclick="editForm.startImport('http://localhost/index.php/admin/import/start/key/91bb0c93f59a2a5cb4bb42aee557e081/', 'import_file');">-->
<!--    <span><span><span>Import</span></span></span>-->
<!--</button>-->

<a href="<?php echo $this->getUrl('magecom_importexport/adminhtml_import/index') ?>" 
   class="scalable save" 
   style="background: #ffac47 url('images/btn_bg.gif') repeat-x scroll 0 100%;
color: #fff;
font-weight: bold;
padding: 4px;
text-decoration: none;
border-color: #ed6502 #a04300 #a04300 #ed6502;
border-style: solid;
border-width: 1px;">Start Import</a>
